[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Devin AI <158243242+devin-ai-integration[bot]@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = {extras = ["standard"], version = "^0.121.2"}
psycopg = {extras = ["binary"], version = "^3.2.12"}
python-multipart = "^0.0.20"
bcrypt = "^5.0.0"
email-validator = "^2.3.0"
psycopg2-binary = "^2.9.11"
sqlalchemy = "^2.0.44"
geoalchemy2 = "^0.18.0"
requests = "^2.32.5"
python-dotenv = "^1.2.1"
apscheduler = "^3.11.1"
shapely = "^2.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
